fix: update dead link
googleapis/java-logging-logback pull request #414
Opened 2021-05-18 07:45 UTC by simonz130

- [ ] Appropriate docs were updated (if necessary)

Fixes #393 ☕️

2021-05-18 21:38 UTC, daniel-sanche requested changes

2021-05-18 21:38 UTC, daniel-sanche commented on README.md
> +[product-docs]: https://cloud.google.com/logging/setup/java/
This appears to be a 404. Should it be https://cloud.google.com/logging/docs/setup/java?

2021-05-18 22:02 UTC, simonz130 commented on README.md
> +[product-docs]: https://cloud.google.com/logging/setup/java/
updated

2021-05-19 01:18 UTC, nicoleczhu approved these changes
LGTM

I dont think this file will be overwritten given : https://github.com/googleapis/java-logging-logback/blob/0a1087f8029d85a29ec2e1bd3f283b927a483089/synth.metadata#L18

2021-05-19 04:22 UTC, merged