Add service context (name/version) for Error Reporting
googleapis/java-logging-logback pull request #83
Opened 2020-04-16 16:02 UTC by chetan

When using the latest build (117-alpha), exceptions which are sent to Error Reporting will show up as a service called `STACKDRIVER_SERVICE_IS_UNDEFINED` since it is not currently being set. This PR adds both the service name and version options to the appender.

2020-06-24 18:54 UTC, chetan commented
FYI - the earlier force push was to rebase/fix the conflict in the README file. Not sure why it is showing as conflicted again, the diff seems fine. I will try rebasing it again.

2020-06-24 19:01 UTC, simonz130 commented on src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
> +   * If NULL, errors will be reported as "STACKDRIVER_SERVICE_IS_UNDEFINED".
Where is "STACKDRIVER_SSERVICE_IS_UNDEFINED" coming from?
There is no such a thing as Stackdriver anymore - it's called "Cloud Error Reporting" and "Cloud Logging" for our purposes.

2020-06-24 19:46 UTC, chetan commented on src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
> +   * If NULL, errors will be reported as "STACKDRIVER_SERVICE_IS_UNDEFINED".
When did it get renamed? When this PR was submitted on April 16, the service name was showing up in the UI console as noted. I'm guessing that if the value is null it will still show up as some `UNDEFINED` value.

2021-07-21 17:39 UTC, hkothari commented
Any way I can help get this merged? I'm very interested in this feature. Happy to update/address any comments if there are specific blockers to merging this.

2021-09-22 13:00 UTC, minherz requested changes
Hello Chetan,
Thank you for submitting this PR. I understand that you are looking for providing two fixed fields to the error report. While the solution is sound, it is ad-hoc to your current needs. If in future you would need to add another field, it will require another change of the library.
I would like to ask you to revise the implementation to make it supporting a collection of labels in the form of the {name: value} pairs. Such solution is extendable and can serve multiple users.

2021-09-22 13:21 UTC, chetan commented
@minherz I'm not sure I follow. What other fields might be needed? The [ReportedErrorEvent](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report) type does not currently have any additional fields. These aren't arbitrary fields but **required** context for the event data which is currently missing.

2022-01-10 09:13 UTC, minherz commented
@chetan until the comments are addressed, you can customize the behavior of the logback appender using enhancers.

2022-01-10 14:53 UTC, chetan commented
@minherz I'm no longer working on the project which was using this change and won't easily be able to test any changes here at this point. I think the best way forward at this point is to simply close this out.

2022-01-10 14:53 UTC, closed without merging